### PR TITLE
Fix exception from missing "this" variable

### PR DESCRIPTION
**Pull request by cyrozap**
There's probably a better solution than the hack I've made, but the code kept raising exceptions during configuration and I wasn't sure how else to solve it.

### CODE REVIEW

**Comment by lr-m** [comment]
Thanks for the PR! Out of curiosity, what exceptions were you getting during configuration? And what Ghidra version are you running?

**Comment by cyrozap** [comment]
I'm running Ghidra 11.0.3, since that's the latest in my distro's repositories (Arch Linux, btw).

Here's one example of the exceptions I was getting:

```
Traceback (most recent call last):
  File "/home/cyrozap/ghidra/scripts/GhidrOllama/GhidrOllama.py", line 393, in <module>
    main()
  File "/home/cyrozap/ghidra/scripts/GhidrOllama/GhidrOllama.py", line 368, in main
    choice = this.askChoice("GhidrOllama", "What you want to ask the {0} model:".format(model), choice_strings, "Question Selection")
  File "/home/cyrozap/ghidra/scripts/GhidrOllama/GhidrOllama.py", line 368, in main
    choice = this.askChoice("GhidrOllama", "What you want to ask the {0} model:".format(model), choice_strings, "Question Selection")
NameError: global name 'this' is not defined
```

**Comment by lr-m** [comment]
Can you test the alternative-fix branch and see if the issue is still there? I can't seem to make the issue happen on my system, I was doing some weird stuff with 'this' so replaced it with a single 'this' I give to config in the main script which should hopefully iron out the weirdness

**Comment by cyrozap** [comment]
The alternate fix doesn't work for me:

```
Traceback (most recent call last):
  File "/home/cyrozap/ghidra/scripts/GhidrOllama/GhidrOllama.py", line 391, in <module>
    CONFIG = Config(this)
NameError: name 'this' is not defined
```

**Comment by lr-m** [comment]
Should be fixed now, moved the config back into the main script, it seems that using 'this' to get the script instance is a pretty new feature so i just removed the need for it. Have tested the alternative-fix branch down to 10.3 so should be all good!

**Comment by cyrozap** [comment]
That worked, thanks!

**Pull request merged**
